name: Release workflow

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP with composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Build project
        run: |
          cd /home/runner/work/pdf/
          rm -r pdf/.git* pdf/tools
          tar -zcvf pdf-${{ github.ref_name }}.tgz pdf

      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: pdf-${{ github.ref_name }}.tgz
          path: /home/runner/work/pdf/pdf-${{ github.ref_name }}.tgz
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: /home/runner/work/pdf/pdf-${{ github.ref_name }}.tgz
          body: "New release is available"
          name: ${{ github.ref_name }}
          draft: true
          generate_release_notes: true